BINANCE_URL = "https://api.binance.com/api/v3/klines"
SYMBOL = "BTCUSDT"
INTERVAL = "30m"
LIMIT = 1000
DAYS = 2900
# CSV_PATH = '/home/sebi/BTC_Price_Predict/LSTM_Model/dataset/bitcoin_binance_30min_1_1_2018.csv'
CSV_PATH = '/home/sebi/BTC_Price_Predict/LSTM_Model/dataset/bitcoin_binance_30min_1_3_2017.csv'
MODEL_PATH = '/home/sebi/BTC_Price_Predict/LSTM_Model/model/lstm_btc_model_30_2.h5'
SCALER_PATH = '/home/sebi/BTC_Price_Predict/LSTM_Model/model/scaler.pkl'